### PR TITLE
fixed #cocos-engine/16594: Missing abstract keyword for AbstractedConstructor in cc.d.ts

### LINKED ISSUE #16594: getComponent() can't support   abstract class.
### Cocos Creator version

3.8.1

### System information

all

### Issue description

getComponent() can't support   abstract class.

2.4.x has support this feature.

### Relevant error log output

_No response_

### Steps to reproduce

` node.getComponent(OneAbstractClass)` ,  vscode reports error message.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dumganhar**
Fix: https://github.com/cocos/cocos-engine/issues/16594

The bug was probably trigged by this PR: https://github.com/shrinktofit/gift/pull/26 since it hardcode the modifer to undefined.

### CODE REVIEW

File: source/recast.ts [hunk 1]
```diff
@@ -769,7 +769,7 @@ export function recastTopLevelModule({
             );
         } else if (ts.isConstructorTypeNode(type)) {
             return nodeFactor.createConstructorTypeNode(
-                undefined,
+                recastModifiers(type.modifiers),
```
Comment (dumganhar) [inline source/recast.ts:772]: Modifier `abstract` keyword was missing here since it's undefined before.

**Review by minggo — APPROVED** [review]
